### ISSUE TITLE
http服务监听了两个端口(测试/发布)；有没有办法判断同一个http请求是访问那个端口的？

### ISSUE THREAD

**Issue by hug2008** [webcpp/hi-nginx#10]
如conf中
http
{
server {listen       80; }

server {listen       8080; }
}

http服务监听了两个端口(测试/发布)；有没有办法判断同一个http请求是访问那个端口的？

namespace hi::request (c++) 如何添加扩展？

**Comment by webcpp** [comment]
第一个问题，我是这样理解的:ngx_headers_more这个可以添加请求头，你可以在在其中一台中添加，另外一台不添加，然后读取判断。
第二个问题，我想继承就可以了

**Comment by webcpp** [comment]
第一个问题更简单的方法是用rewrite重写uri把端口写到form中。这样就不用ngx_headers_more了。而且更自然。

**Comment by hug2008** [comment]
对nginx机制不熟悉

rewrite重写uri把端口写到form中？

具体如何实现呢？

**Comment by webcpp** [comment]
你看看rewrite的用法，就添加个?port=8080
到原来的uri后面即可

**Comment by webcpp** [comment]
https://nginx.org/en/docs/http/ngx_http_rewrite_module.html
