### ISSUE TITLE
Question: Does the cpp lib runs as a different  process.

### ISSUE THREAD

**Issue by Dhua-v** [webcpp/hi-nginx#15]
As i am concerned about performance, want to know that if the c++ application code "runs as a seprate process and  communicates via Inter process communication with Nginx" or "it is loaded into nginx as .so file, like a plugin does."

I am very excited to know.

**Comment by webcpp** [comment]
It is loaded into nginx as .so file, like a plugin does.

**Comment by webcpp** [comment]
```cpp
#include "servlet.hpp"
namespace hi{
class hello : public servlet {
    public:

        void handler(request& req, response& res) {
            res.headers.find("Content-Type")->second = "text/plain;charset=UTF-8";
            res.content = "hello,world";
            res.status = 200;
        }

    };
}

extern "C" hi::servlet* create() {
    return new hi::hello();
}

extern "C" void destroy(hi::servlet* p) {
    delete p;
}
```
```nginx
            location = /hello {
                hi cpp/hello.so ;
            }

```
[config example](https://doc.hi-nginx.com/00/0002.html)

**Comment by Dhua-v** [comment]
What about java python, at what point they do Inter process communication.

**Comment by webcpp** [comment]
All are plug-ins.
All are embedded.
No inter-process communication is required.

**Comment by Dhua-v** [comment]
Then how java and c++ nginx communicate.
The java byte code could not communicate with c++ compiled code. 

All I mean is java code is not compiled to .so
Then how can it communicate with nginx that way without IPC.

**Comment by webcpp** [comment]
hi-nginx calling java with JNI.

**Comment by Dhua-v** [comment]
ok
that solves
this is amazing then
Wow 
maza agya

**Comment by Dhua-v** [comment]
Also, is there any way to use async functions?
