### ISSUE TITLE
fatal error: jsoncons/basic_json.hpp: No such file or directory

### ISSUE THREAD

**Issue by KeymanHuang** [webcpp/hi-nginx#17]
version：release-2.2.5
./configure后执行make，报错fatal error: jsoncons/basic_json.hpp: No such file or directory

**Comment by webcpp** [comment]
完整的configure命令是什么，有无clean先。

**Comment by webcpp** [comment]
这边一直用install_demo.sh构建，没有出现相关问题。你可以copy该文件，修改为适合自己的my_install_demo.sh试试

**Comment by KeymanHuang** [comment]
谢谢 已解决
