### ISSUE TITLE
sudo make install error

### ISSUE THREAD

**Issue by shawvi** [webcpp/hi-nginx#2]
cp -R /include '/usr/local/nginx/'
cp: 无法获取'/include' 的文件状态(stat): 没有那个文件或目录
objs/Makefile:1170: recipe for target 'install' failed

1. cp -R /include /usr/local/nginx/ 是否应该为：cp -R include /usr/local/nginx/ 
2. 如果1成立，hi-nginx 目录下并没有include目录

**Comment by webcpp** [comment]
如果你打算安装在/usr/local/nginx，请参考install_demo.sh中--prefix=/usr/local/nginx。
我刚才测试来安装在这个位置，没有问题。不要自己修改objs中的任何代码。
make clean && ./install_demo.sh && sudo make install
即可。
