### ISSUE TITLE
make的时候 报php错误

### ISSUE THREAD

**Issue by 423230557** [webcpp/hi-nginx#3]
make的时候 报php错误   找不到php/main/php.h  文档没说如何安装php7

**Comment by webcpp** [comment]
readme有安装php7的说明啊

**Comment by 423230557** [comment]
About php7+ install

Please change configure :

ac_fn_c_check_decl "$LINENO" "isfinite" "ac_cv_have_decl_isfinite" "#include <math.h>
"
if test "x$ac_cv_have_decl_isfinite" = xyes; then :
  ac_have_decl=0
else
  ac_have_decl=0
fi

**Comment by 423230557** [comment]
这个改configure，是哪个configure,是增加还是覆盖？改完之后执行configure么？

**Comment by webcpp** [comment]
改完之后执行configure。
如果是only-php分支，不需要改。

**Comment by 423230557** [comment]
看不太懂怎么改，用onlyphp分支下的 configure覆盖master 然后编译可以吗？

**Comment by webcpp** [comment]
很容易该的。搜索ac_cv_have_decl_isfinite
会找到相关位置。把ac_have_decl=1的改为等于0即可。
两处均要等于0.

**Comment by webcpp** [comment]
如果只是用php,直接用only-php分支。

**Comment by 423230557** [comment]
cpp的编译通过了，想做一个不带php的分支，需要注意修改哪些文件呢？

**Comment by webcpp** [comment]
切换到onlycpp分支

**Comment by webcpp** [comment]
只有master分支要改php7安装部分的脚本，其他分支都无需改。

**Comment by 423230557** [comment]
/usr/bin/ld: 找不到 -lphp7
这个make报错是 我没编译好php么？   debian已经make install 了php7.0

**Comment by 423230557** [comment]
带php的 编译太难了

**Comment by webcpp** [comment]
configure php7 时要使用--enable-embed选项

**Comment by webcpp** [comment]
https://yq.aliyun.com/articles/278690
