### ISSUE TITLE
ubuntu 18  gcc 7 编译错误

### ISSUE THREAD

**Issue by javacty** [webcpp/hi-nginx#6]
启用php支持:
 ./configure --prefix=/opt/hi    \
--enable-http-hi-cpp=YES       \
--enable-http-hi-python=NO  \
--enable-http-hi-lua=NO         \
--enable-http-hi-java=NO        \
--enable-http-hi-php=YES        \
--add-module=ngx_http_hi_module  \
--with-threads --with-file-aio
======================================================
objs/ngx_modules.o \
-lhiredis -lphp7 -ldl -lpthread -lcrypt -lstdc++ -lpcre -lssl -lcrypto -ldl -lpthread -lz \
-Wl,-E
objs/addon/php-x/variant.o: In function `php::Variant::jsonEncode(long, long)':
variant.cc:(.text+0x4ac): undefined reference to `json_globals'
variant.cc:(.text+0x4ba): undefined reference to `json_globals'
variant.cc:(.text+0x4ca): undefined reference to `php_json_encode'
variant.cc:(.text+0x4d0): undefined reference to `json_globals'
objs/addon/php-x/variant.o: In function `php::Variant::jsonDecode(long, long)':
variant.cc:(.text+0x5a8): undefined reference to `json_globals'
variant.cc:(.text+0x632): undefined reference to `php_json_decode_ex'
variant.cc:(.text+0x6b2): undefined reference to `json_globals'
collect2: error: ld returned 1 exit status
objs/Makefile:346: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory '/opt/hi-nginx'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
====================================================
另外还想请教下，最近出了个nginx unit，和你的hi-nginx异同，谢谢

**Comment by webcpp** [comment]
首先确定你按照readme的有关说明，安装好了php7+,--enable-embed=shared 
其次留心ldconfig 配置
一般情况下，做好以上两点，编译成功是没有问题的。
最后，关于与unit的比较。我没有关注过unit，hi-nginx最初是为了写c++ servlet，后来逐步扩展成现在的样子。粗略的了解下后，窃以为两者间最大的不同在于：unit为不同于nginx的另一种产品和知识系统，而hi-nginx所做就是尽量维持和发展nginx已有的知识系统。至于性能比较，我没有研究，但我十分信任nginx。
祝你愉快。

**Comment by javacty** [comment]
另外还想问下，nginx配置中必须指明运行哪个php文件，不能根据url确定执行哪个php文件吗？
hi-nginx+php-embed比nginx+php-fpm效率高吗？

**Comment by webcpp** [comment]
首先，必须源包编译安装php7.包管理器的不行。
其次，readme中说明了可以不指定php文件，指定目录即可，会自动搜索url确定的php文件。这时，需要文件名与servlet同名。其实这样反倒不如我在readme中推荐的单文件入口方式，而且不会有性能损失。
最后，关于性能，它比反向代理肯定要高，而且内存消耗低，更稳定。

**Comment by javacty** [comment]
小白我这两天找了下，上面错误是因为-lphp7 没找到libphp7.so文件，因为我的编译php安装路径不是readme里给的路径，可以通过修改hi-nginx/ngx_http_hi_module/config文件，55行，添加路径，比如我的：
CXXFLAGS="$CXXFLAGS `/opt/php725_gcc/bin/php-config --includes`"

另外如果用gcc8编译的话：
修改hi-nginx/auto/cc/gcc的169行: CFLAGS="$CFLAGS -Werror=format-security"
修改src/os/unix/ngx_user.c的26行，将其注释，//cd.current_salt[0] = ~salt[0];

**Comment by webcpp** [comment]
强烈建议不要自己修改源代码，找不到php7库的问题，可以很容易通过其他方法解决，比如设置ldconfig。

**Comment by javacty** [comment]
谢谢作者回复，昨天试了下ldconfig无效，百度了下，好像gcc只搜索/usr/local/lib和/usr/lib.

另外今天测试了下，编译php时，json不能作为外置扩展（json.so）, 不过编译ranggo的php-x项目是可以的，有点奇怪？

**Comment by webcpp** [comment]
关于ldconfig，请参考https://m.aliyun.com/yunqi/articles/278690，是可以配置自己的库路径的

**Comment by webcpp** [comment]
https://m.aliyun.com/yunqi/articles/278690
关于ldconfig，请参考以上链接。

**Comment by webcpp** [comment]
是可以自己配置库搜索路径的

**Comment by webcpp** [comment]
是可以自己配置库搜索路径的

**Comment by webcpp** [comment]
是可以自己配置库搜索路径的

**Comment by webcpp** [comment]
php7的编译是先于hi-nginx的，其问题与后者无关
