### ISSUE TITLE
小白问题

### ISSUE THREAD

**Issue by hug2008** [webcpp/hi-nginx#7]
小白问题：
 1. 如何部署到公网并绑定域名？
 2. 如何支持HTTS访问；
 3. 希望给出一个上传&下载文件的例子(C++)；

**Comment by webcpp** [comment]
前两个问题的答案就是普通nginx的答案。hi-nginx是nginx的超集，nginx下有的东西、有的操作，在hi-nginx下都是有效的。因此，你可以自己搜nginx和https的部署问题。注意编译是要启用http2。把你不需要支持的语言用NO关掉，直接运行install_demo.sh一般就是可以的。比如：

```shell
./configure                                                         \
                --with-cc=gcc                                       \
                --with-http_ssl_module                              \
                --with-http_v2_module                               \
                --prefix=/usr/local/nginx                           \
                --enable-http-hi-cpp=YES                            \
                --enable-http-hi-python=NO                         \
                --enable-http-hi-lua=NO                           \
                --enable-http-hi-java=NO                           \
                --enable-http-hi-php=NO                            \
                --with-http-hi-python-version=python3               \
                --with-http-hi-lua-version=lua5.1                   \
                --add-module=ngx_http_hi_module                     \
                --add-module=3rd/nchan-1.1.14                       \
                --add-module=3rd/nginx-rtmp-module-1.2.1   
```
然后看看以下几篇文章：
- http://www.cnblogs.com/yanghuahui/archive/2012/06/25/2561568.html
- http://www.cnblogs.com/tintin1926/archive/2012/07/12/2587311.html
- https://blog.itnmg.net/2016/03/03/letsencrypt-ssl/
一般很快就可以搞定前两个问题了。网上很多，多看看并尝试就可以搞定。

第三个问题其实更简单。所有http(s)提交的表单数据，都在hi::request的成员变量form中，这是个普通的STL容器，你可以搜索和获取表单元素。比如以下表单：

```html
        <form name="upload" method="POST" enctype="multipart/form-data" action="/demo/form">
            <input type="file" name="upload_1"><br>
            <input type="file" name="upload_2"><br>
            <input type="text" name="test_key" placeholder="test">
            <input type="submit" name="submit" value="Upload">
        </form>
```
这个表单会提交三个变量，分别为upload_1,upload_2和test_key。它们都可以在form中找到。对上传文件部分，前两个变量的值是被上传的临时文件的地址，临时文件夹是hi-nginx安装目录下的temp，你可以从form中获取值，然后把它们移动到你想的任何地方或者删除它们。
你可以参考我关于hi-nginx-python的一篇关于上传的文章：
- http://www.cnblogs.com/hi-nginx/p/8663291.html
最后说明下：
- temp文件夹必须有权限写
- client_max_body_size可以控制能上传的文件大小
- c++ 移动文件可以使用boost.filesystem，当然你也可以使用其他类库或者函数，比如：https://stackoverflow.com/questions/20161243/how-to-move-file-from-one-folder-to-different-folder-in-linux

**Comment by webcpp** [comment]
the end
